Repository Graylog2/graylog-plugin-threatintel, pull requests merged in 2020-11, with the labels that each got.

#176 Update yarn lockfiles preparing for release of 4.0.
  yarn.lock
Labels: ready-for-review

#175 Use ESLint settings configured in eslint-config-graylog
  package.json
Labels: improvement, ready-for-review

#180 Update WHOIS plugin to better handle cases with multiple results
  src/main/java/org/graylog/plugins/threatintel/whois/ip/InternetRegistry.java
  src/main/java/org/graylog/plugins/threatintel/whois/ip/WhoisIpLookup.java
  src/main/java/org/graylog/plugins/threatintel/whois/ip/parsers/ARINResponseParser.java
  src/main/java/org/graylog/plugins/threatintel/whois/ip/parsers/WhoisParser.java
  src/test/java/org/graylog/plugins/threatintel/whois/ip/parsers/ARINResponseParserTest.java
Labels: bug, java, ready-for-review

#181 Backport updates to WHOIS data adapter
  src/main/java/org/graylog/plugins/threatintel/whois/ip/InternetRegistry.java
  src/main/java/org/graylog/plugins/threatintel/whois/ip/WhoisIpLookup.java
  src/main/java/org/graylog/plugins/threatintel/whois/ip/parsers/ARINResponseParser.java
  src/main/java/org/graylog/plugins/threatintel/whois/ip/parsers/WhoisParser.java
  src/test/java/org/graylog/plugins/threatintel/whois/ip/parsers/ARINResponseParserTest.java
Labels: backport, feature, ready-for-review

#182 Backport updates to WHOIS data adapter
  src/main/java/org/graylog/plugins/threatintel/whois/ip/InternetRegistry.java
  src/main/java/org/graylog/plugins/threatintel/whois/ip/WhoisIpLookup.java
  src/main/java/org/graylog/plugins/threatintel/whois/ip/parsers/ARINResponseParser.java
  src/main/java/org/graylog/plugins/threatintel/whois/ip/parsers/WhoisParser.java
  src/test/java/org/graylog/plugins/threatintel/whois/ip/parsers/ARINResponseParserTest.java
Labels: backport, feature, ready-for-review
